apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:94g8dC5nI3Xr1Z4Po9T4snetwEO0jUHbCWy745wEUa4cexHJKCzuZTgtNp5hhtJc0DjmtaI9TPR3qFIY8LdybwfZpbEDw+jwRusHMDBxtxC0THJWS5wZWHOFCyQ0ev6DTfQugLsIvRbyVF13FxX98FoHeq4qC1FORdqWHJwwELgbmnICz+jtMwx9zVm4FXsJ9E+3LmLXNSri9W9EGvcXxDcIc4WYGPJOZTAUEeCmb0yR3oLGBhJ4oRbTEeUB6xHg1nKX5et264Q7iy/QQyjBNUjIzndmZmh1iZi3p6v0AIvzvSdFn+DCW1TZEnOKF8/ZqQCiHlYpv/Y2pp3h+ITBRxRsCgb6gRDbx3HE3stx5OcLTUH4rSUWxxbVkN/zCH22q542dfhNSuYuL7G+HXVdWIossE7ibeeHy43b3obD8l8=,iv:NtX0lIM9D6dxyzw4NcGNjFzPlxzzZVXTsrpXUhIkDgQ=,tag:vn46KkHC3bAhB9bFY/h07w==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: default
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacDVkbmZUK25tMFlBUHgr
            SzBxYUVydUI2RThrWk0vLzc2NUJIWFpwQ2xNCmd1Zlk4dE1kbktRUkR1UG5STk5P
            aW1pVGE3TUMvQVp4b2lmUXlyVWFxOUEKLS0tIFUzMnM2eWx5eGxQMy9VTkZzWHNU
            NnVQNWpwVkk0NSs5MVMzSEFjVFhId28KAy4h6OTWr1+YNwgJNQe/aK7K500tAYTg
            g0lFKbPQslEiadCKGvFZPmi0SoOn7AIqYT5OJ65CGhILNQkQ2IC8Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wr0plcjyvqxyv44x5guuk830ke9mqkfrhkn5rezwre232lu9gv7qq5phnz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T23:58:27Z"
    mac: ENC[AES256_GCM,data:gEYyR7WuUFogh2PRM34k6bOa2ZbDS46TB+/xdlADhoypk1PzKNVVLgbcJUb+7R6lAOCanxYANlt1pH6hRGdpZ059P7z6eVdag4QpstgD76S0+PIs1RbFOKEl4hEAtzonIJzDsLLtEKNOSnYaPqljv+0PQVZcu4SB/lXG2HsHckk=,iv:d8Mgqzrz7qPz9TnOMX4ZfiUIxY9Dx4hxT2nias06y8s=,tag:Os6ctHEPpMqdMzkkyqpwUw==,type:str]
    version: 3.13.1
