apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:S/aazzrHXikR+GG/gZw86HvJMmpv31Q/P8Meu3x/Wx8hVQvUWNcyi90s88mp7+gLmjD+YNRag9i5BlC1Dhz+8YW78FSSgfDyYnMfunur7TbUH1OuCUoVyodKrNnOt/AjLuHeIsn/9IyrSWRJeO6TtWGfNa0K7WLNCcRBi9ens5P4nOALKTs5DmvHvq1A/2QrdJcICjTKq3fdM0nz67sm8hQI8l2cLzd+elOxoF/ihdQ1IxWT064wzAp6IdC9ga98tICU70kO/LDE8oR5vPlXREQTKfRw8KuwEHt0FP92R53twxFgma/WwlXMeVydn5aOZlSSxMzZE8W2k2jy0rzC4R+lIC3+DqJ99aJWBECjKGXB1tDR8bfZuMq0t3w=,iv:07HO3IrC+/HO2gJDJhocgBLXxbflOufRsECAcTt912g=,tag:nb5Ehgs1RhkjF4IKxbHYqA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: default
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnoySHByOGtSZ0tRZVhK
            RnFKMFNZTFlaTnhNbUN5MmcwbTNSVUxXZ3k4Ck12YXZER2hHYXlyalJYNzR0SXl6
            MDRuYTZDYzJEcVlPc0cwYUZEZUxSWkUKLS0tIE5URUtHOEVqNFhrVGMwdXpxYkR6
            SkovWmlnWW1WMTREbTc3TllwVXlVMWMKgmcAUQKNp+/sZL/RB1O9pVNnh+jCK68m
            m0xAvKuiuvbjCb3caJXTRVjvavaOeUo3kSRP8+aGIXfy9/2rBJFttw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zm5p7pqvtvd0pp2aautfedxrkdrukd2r0kk76s35k57lagnpwgvq30fr7d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T11:28:01Z"
    mac: ENC[AES256_GCM,data:ctqeoa8JxEXSBYm3NJewCGkaCyaq6aqorz15uTBgO0joeibUi/PDyBA0IztxWlb/lwpZciosWJ6HO120b5MFJkOT5y6uUZ/BVzakW+dE7RWNPo58M1a1q6gBNoB4sdIJanSPWC/XHU9AC6UW3AW7tMH8MLjSI42hechXhfb9XXg=,iv:xGLpH3DXcKL2dnhg1ntDJcwNOyI3FXsTo11gEtQ8Vf0=,tag:eZ1TwRdO29bH9vdXpeV1+Q==,type:str]
    version: 3.13.1
