apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:VIJMkRS/Vi9iFp/4qCOWKB96aFF5EqehKbd9/9yRnRJEjTM9KzDBzfACpFVzj9PocMQnteD4swQPcntLAnqWCs4J+b5lwBsv8ejFdVYxyBzCotRgqmmYcKMccGsNbFB8j6X+WfQRg2y3DwmccFmnLnGpr3V/CpCgMs7SAFpoQkXaLvfAW0eRZoR/iZzprYiZAwaD5wY4PmCSyl0ExTRdQLvKPCbLxeIvUz5uV0jdmmuh8rLmOeYh+zIzsNJgotiDQ0Rl3CIStiiNgfPJzvRzJ8tA1xHj6Rw8EX8exS2sslVKpseTIBNHSKgIKdKdSG8TJK7s/zPHBIitCMo8yZG3fg1Eu8IMXrLdpLy1/Hc0EjU3Kj7LTce+aO8BFTXHk5N3,iv:HY3DyaTVTk6i2Tdq1pIvtmNqer6Ma2jJaj/ntVZlr80=,tag:gXFpV3kH1XnXoHpt00FXXg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: default
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdHBNQldnVkh0YnI0V2Z4
            ZmRoa3ZsbFI4TlRmNitpWlBmanpCNzI3ZVdjCkJibHowV0ZIaEdUMzBNd1p5bmZP
            RXd5OXh0cjdnenpZZ21YWnBycWlYWHMKLS0tIDB1blBmeStQa3MxYTN0Ui9DRHJz
            ZDZ1eWxFMHY2dW1MVnpYQ2lzR0tRM3MK7WjEFOzeOxz9Rou8cCxWGO+RbtvtPEjy
            yrtRDBMqZ5aPKlOm5zkpKPdCDjBKwT5jS+F4L9Oy+6Qo8WbMncH1Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wr0plcjyvqxyv44x5guuk830ke9mqkfrhkn5rezwre232lu9gv7qq5phnz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T00:16:55Z"
    mac: ENC[AES256_GCM,data:59AepU0jeLHimTPKBInmND2Ca1czricnury9JDRvNDeSlOeriQWhwTx0GUE/l9INASeDGSoZo9FYW10us1JsFglfXblhVDUszzK0fNpWl8rf6oHWrzHsy+O/Vi6BnkdXiy0ydFVDMKlIJ/8lj6tjbsqYctpul3RQUaBSCprnF70=,iv:s8gNKYeTN7Ru/pbR7Z/U+92KChoKYGEGo59y2pTh5sY=,tag:JG1n+LX3EE2VDkQVKqjslg==,type:str]
    version: 3.13.1
